### ISSUE TITLE
hi,here is a problem about parse

### ISSUE THREAD

**Issue by FirePhenix** [alexeyxo/protobuf-objc#22]
i'm make a pb object send to server, but server can't parse

here is my client code :  
IMLoginReqBuilder *login = [IMLoginReq builder];
        [login setUserName:@"test"];
        [login setPassword:@"123456"];
        [login setClientType:ClientTypeClientTypeIos];
        [login setClientVersion:clientVersion];
        [login setOnlineStatus:UserStatTypeUserStatusOnline];
        IMLoginReq *test = [login build];
        [dataout writeBytes:test.data];

and C++ server print :   
Can't parse message of type "IM.Login.IMLoginReq" because it is missing required fields: (cannot determine missing fields for lite message)

**Comment by alexeyxo** [comment]
Сan you to compare number of sent and received bytes? In this case, hard to say what the problem is! Can you show ```proto``` file? I have a server running in JAVA using HTTP protocol, and I have never met such problems.

**Comment by FirePhenix** [comment]
Here is my problem .. , I'm so apologize !!
