### ISSUE TITLE
Modern Objective-C Syntax

### ISSUE THREAD

**Issue by JustinDSN** [alexeyxo/protobuf-objc#23]
Are there any plans to adopt the 'Modern Objective-C Syntax' as described in: https://developer.apple.com/library/ios/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html#//apple_ref/doc/uid/TP40014150-CH1-SW2

I think the few main items are:
* ```NS_DESIGNATED_INITIALIZER```
* ```instancetype``` instead of ```id```

**Comment by alexeyxo** [comment]
Where should be used ```NS_DESIGNATED_INITIALIZER``` in your opinion?

**Comment by JustinDSN** [comment]
@alexeyxo after closer inspection, it appears the ```NS_DESIGNATED_INITIALIZER``` it doesn't need to be used anywhere since only the init method is implemented in the .m file. 

Thanks for adding instance type with https://github.com/alexeyxo/protobuf-objc/commit/8ce72ed85a0295f93b9032f524e13785a5de3cdc.

**Comment by alexeyxo** [comment]
Thanks.
