### ISSUE TITLE
.proto.h & .proto.m file compile error

### ISSUE THREAD

**Issue by emp-heng** [alexeyxo/protobuf-objc#24]
when i generate .h & .m file accord to .proto, there are some errors:  
Xltire_protocol.pb.m:1056:32: error: type of property 'result' ('MemberList *') does not match type of accessor 'result' ('SInt32' (aka 'int'))
@property (strong) MemberList* result;
                               ^
In file included from /Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.m:3:
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.h:385:1: note: declared here
- (SInt32) result;
^
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.h:386:1: error: type of setter must be void
- (MemberListBuilder*) setResult:(SInt32) value;
^
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.m:1056:32: warning: type of property 'result' does not match type of accessor 'setResult:'
@property (strong) MemberList* result;
                               ^
In file included from /Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.m:3:
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.h:386:1: note: declared here
- (MemberListBuilder*) setResult:(SInt32) value;
^
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.m:1063:17: warning: incompatible pointer to integer conversion assigning to 'SInt32' (aka 'int') from 'MemberList *' [-Wint-conversion]
    self.result = [[MemberList alloc] init];
                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jay/study/SourceCode/TimSunSales/TimSun/TimSun/Models/GoogleProto/Xltire_protocol.pb.m:1071:15: warning: incompatible pointer to integer conversion assigning to 'SInt32' (aka 'int') from 'MemberList *' [-Wint-conversion]
  self.result = [[MemberList alloc] init];

**Comment by alexeyxo** [comment]
Can you show proto file?

**Comment by emp-heng** [comment]
hi, sorry to reply, below is a part of proto file:
message MemberInfo {
	required uint32 	user_id 		= 1; 
	optional string 	user_name 		= 2;
	optional string 	password 		= 3;
	optional string 	phone 			= 4;
	optional int32 		role_id			= 5;
	optional string		department 		= 6;
	optional MemberSexType	sex			= 7;
	optional uint32		region_id		= 8;
	optional uint32		superior_id		= 9;
	optional AuditStateType	audit_state	= 10; 
	optional uint32		register_time 	= 11;
	optional uint32		update_time		= 12;
	optional string		email			= 13;
}
message MemberList {
	optional int32	res				= 1;
	optional int32	second_type		= 2; //二级命令字，主要是用来区分不同的查找
	optional int32	total_count		= 3;
	repeated MemberInfo	members		= 4;
}
//角色表
message RoleInfo{
	optional uint32	role_id		= 1;
	optional string role_name	= 2;
	optional uint64	auth_value	= 3;
	optional string	description	= 4;
}
message RoleList{
	optional int32	res				= 1;
	optional int32	total_count		= 2;
	repeated RoleInfo roles			= 3;
}

the issuse is solved, when i modify the proto file,        "result" to "res", but i have not get the reason, 
could you tell me why, thanks very much

**Comment by alexeyxo** [comment]
This problem was occurs because the «result» reserved name in Protobuf-Objc. In the latest version problem is fixed.
[Commit](https://github.com/alexeyxo/protobuf-objc/commit/c1dbee68f003f45116ab461091f4041f5e978c8b#diff-4e7364b72ec86dcaf7a38d2de0f7ce0eL945)
