### ISSUE TITLE
Will you support disable readonly property

### ISSUE THREAD

**Issue by dofork** [alexeyxo/protobuf-objc#25]
The following example shows the limitation of current protobuf-objc's implementation.
If there is a message Car:
message Car
{
 optional string brand = 1;
}
the output of objc class will be like this:
@interface Car : PBGeneratedMessage {
@private
  BOOL hasBrand_:1;
  NSString* brand;
}
- (BOOL) hasBrand;
@property (readonly, strong) NSString* brand;

Now you got a car, 
Car *car
If you want to change the car's name, you should do this:
car = [[car tobuilder] setBrand:@"new car brand"].build;
But the new car's memory address is different from the original one.
You can not keep the same pointer(memory address) of car when set a new value for brand by syntax:
[car setBrand:@"new car brand"], because brand is readonly;

Will you support this feature?

**Comment by alexeyxo** [comment]
This is not true. In this case, If I remove ```readonly``` option - thread safety in the pattern ```Builder``` will be broken.
