### ISSUE TITLE
Don't insert #import "ObjectivecDescriptor.pb.h" into generated code?

### ISSUE THREAD

**Issue by wwlinx** [alexeyxo/protobuf-objc#26]
Hi,
I use objectivec_file_options to specify a class prefix in my proto, but the compiler inserts a runtime dependency (#import "ObjectivecDescriptor.pb.h"). As far as I can tell these are proto-compile-time only and don't need to be added to the generated code. I have a patch to fix this, will you take it?

**Comment by alexeyxo** [comment]
Fixed! Thanks a lot!
