### ISSUE TITLE
Compiling error: "PBGeneratedMessage_Builder" not found!

### ISSUE THREAD

**Issue by shannonchou** [alexeyxo/protobuf-objc#29]
protobuf version: 2.6.1
protobuf-objc: 1.9.6

All *.pb.m files raise this error:

Cannot find interface declaration for 'PBGeneratedMessage_Builder', superclass of 'PBLoginResult_Builder'; did you mean 'PBGeneratedMessageBuilder'?

**Comment by shannonchou** [comment]
The example also can't be run.

**Comment by alexeyxo** [comment]
You use the compiler protobuf-objc is from not my repository.

**Comment by shannonchou** [comment]
Sorry，I made a foolish mistake. -_-|||
