### ISSUE TITLE
 file not found

### ISSUE THREAD

**Issue by ninibytel** [alexeyxo/protobuf-objc#33]
Hello when i test the proto.xcodeproj i have this error: 
'ProtocolBuffers/ProtocolBuffers.h' file not found
where it may come

**Comment by alexeyxo** [comment]
I have not updated the example, he does not work.

**Comment by edokeh** [comment]
I met this problem in 1.9.8 too.

**Comment by ddaddy** [comment]
I'm getting file not found for ProtocolBuffers.h in my own project, but the example seems to see it fine.
Any idea why?

**Comment by alexeyxo** [comment]
@ddaddy 
Can you describe in detail how you installed library? 
Or give me example project.

**Comment by ddaddy** [comment]
I've dragged the ProtocolBuffers.xcodeproj to my project, added it to both Target Dependencies and Link Binary With Libraries.

In my project, neither `#import <ProtocolBuffers/ProtocolBuffers.h>` or `#import "ProtocolBuffers.h"` find the file.

**Comment by alexeyxo** [comment]
You should set up "Header Seartch Path" and "User Header Search Path" in "Build Settings".

**Comment by maojj** [comment]
I meet the same problem when I drag the proto.xcodeproj in my project( not by cocoapods).
Because ```ProtocolBuffers.h``` is not in the ```ProtocolBuffers``` folder, So even I add ```Add Search Path```, I get the "'ProtocolBuffers/ProtocolBuffers.h' file not found " error.

My solution:
 1. Make a folder named ```ProtocolBuffers``` under ```/path/to/protobuf-objc/```, and copy ```ProtocolBuffers.h``` to it.
 1.  add ```/path/to/protobuf-objc/``` to "Header Seartch Path" in "Build Settings".

**Comment by ddaddy** [comment]
Thanks guys. I added the header and user header search paths, anyone else looking, make sure to set them to recursive.

Then, for some reason I had to change any `#import <ProtocolBuffers/ProtocolBuffers.h>` to `#import "ProtocolBuffers.h"` and it now compiles.

Thanks
