### ISSUE TITLE
Compiler Warning: 'ns_returns_not_retained' attribute only applies to functions and methods

### ISSUE THREAD

**Issue by JustinDSN** [alexeyxo/protobuf-objc#39]
The NS_RETURNS_NOT_RETAINED annotation is being applied to instance variables and properties.  It should only be applied to methods and functions.

http://clang-analyzer.llvm.org/annotations.html#attr_cf_returns_not_retained

**Comment by alexeyxo** [comment]
Thanks!

**Comment by JustinDSN** [comment]
Cool thanks Alexy
