### ISSUE TITLE
Build Error at common.h

### ISSUE THREAD

**Issue by PoorMe** [alexeyxo/protobuf-objc#40]
Hi there,

(I'm new to github so I hope this is the right way to place a question.)

I am running Xcode 6.1.1 under OS X Yosemite 10.10.2 and wanted to give your ObjC Protobuf implementation a try. I followed your instructions under „Building the Objective-C Protobuf compiler“ 1:1 but got the following error at ./build.sh:
```
[…]
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking google/protobuf/stubs/common.h usability... no
checking google/protobuf/stubs/common.h presence... no
checking for google/protobuf/stubs/common.h... no
configure: error: 
ERROR: protobuf headers are required.

You must either install protobuf from google,
or if you have it installed in a custom location
you must add '-Iincludedir' to CXXFLAGS
and '-Llibdir' to LDFLAGS.

If you did not specify a prefix when installing
protobuf, try
  './configure CXXFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib'
In some 64-bit environments, try LDFLAGS=-L/usr/local/lib64.
```
I cannot even find the above mentioned 'common.h' in the github files (under stubs there are only three files: hash.h, strutil.h, substitute.h) – so I would NOT expect that setting the above suggested flags to change anything. Do I need to download the entire Protobuf C++ (?) library from google? 

Any help would be appreciated.

**Comment by alexeyxo** [comment]
Please look there: https://github.com/alexeyxo/protobuf-objc/issues/32

**Comment by PoorMe** [comment]
Thank you very much for your quick response! I wasn't sure if I understood the discussion in #32 completely, so I decided to retry the entire installation on a "fresh" system and succeeded. I assume that my prior/first attempt failed, because of some conflicts due to a prior installation of protobuf. 
Many thanks though!

**Comment by alexeyxo** [comment]
No problem, thanks!
