### ISSUE TITLE
./build.sh - wrong path for autogen.sh

### ISSUE THREAD

**Issue by benvium** [alexeyxo/protobuf-objc#43]
Following the instructions to run the build.sh file I get:

```
./build.sh: line 5: ./autogen.sh: No such file or directory
```

adding:
```
cd ..
```

to the start of the build.sh file appears to fix it. Perhaps the build.sh file was recently moved?

**Comment by alexeyxo** [comment]
Take a look carefully instruction:
https://github.com/alexeyxo/protobuf-objc#building-the-objective-c-protobuf-compiler
Step 6.

**Comment by benvium** [comment]
oops. my apologies
