### ISSUE TITLE
Trouble compiling for 64bit OSX

### ISSUE THREAD

**Issue by ddaddy** [alexeyxo/protobuf-objc#46]
I've added this to a framework for an OS X & iOS app, however i'm having trouble building it for the App Stores.
I get the error `ld: symbol(s) not found for architecture arm64` when trying to build for iOS and a similar x86_64 error for OS X.
Is there a reason this wouldn't compile for 64 bit?

Thanks

**Comment by alexeyxo** [comment]
I need more information... This error can occur for many reasons.
