### ISSUE TITLE
Redefinition of 'Type' as different kind of symbol

### ISSUE THREAD

**Issue by CyberCelly** [alexeyxo/protobuf-objc#47]
Hi,
I'm facing the error message "Redefinition of 'CommonInfo' as different kind of symbol" after generation of source code for protobuf message.

First proto file source **upload_data.proto**:
```
package Project.Protocol;
import "common_info.proto";

message UploadDataRequest
{
	optional string ServiceId = 1;
	repeated CommonInfo CommonInfoData = 2;
};
```
Second proto file source **common_info.proto**:
```
package Project.Protocol;

message MultiValue
{
	optional string Property = 1;
	optional string Value = 2;
	optional string Label = 3;
};

message CommonInfo
{
    optional string Id = 1;
    optional bytes Data = 2;
    repeated MultiValue Properties = 3;
};

message CommonInfoRequest
{
    optional string ServiceId = 1;
    repeated CommonInfo Data = 2;
};
```
Generated code contains forward declarations:
```objective-c
#import "Common_info.pb.h"
// @@protoc_insertion_point(imports)

@class CommonInfo;
@class CommonInfoBuilder;
@class CommonInfoRequest;
```
I suppose that this is somehow related to forward declarations. Could you please advise how to fix it and make generated code compilable?

**Comment by alexeyxo** [comment]
I don't understand, in what place the problem?

**Comment by CyberCelly** [comment]
When I include upload_data.pb.h in my project and try to use generated UploadDataRequest I get the error "Redefinition of 'CommonInfo' as different kind of symbol"

**Comment by alexeyxo** [comment]
I can't reproduce this problem. Your example works fine in my test project..

**Comment by CyberCelly** [comment]
The issue is fixed. The code has enum which has member with the same name as generated by the protobuf compiler. Sorry for worries.
