### ISSUE TITLE
Example Project does not compile / Cannot find PB symbols from ProtocolBuffers when compiling framework

### ISSUE THREAD

**Issue by victorcotap** [alexeyxo/protobuf-objc#48]
Hi

I'm using Xcode 6.3.2

When cloning repository and trying to compile the Example project, I get this reference error in descriptor.pb.h
![screen shot 2015-05-27 at 11 30 48 am 1](https://cloud.githubusercontent.com/assets/7770859/7844273/0c8bdcd2-0464-11e5-81f5-ee7ab778a417.png)

I've originally tried to include ProtocolBuffers in my own dynamic framework just by adding the ProtocolBuffers project file to my dynamic framework project and then linking the libProtocolBuffers in the link build phase.
Every time during compilation it references some PB symbols it cannot find them.

Using your ProtocolBuffers for swift works in terms of referencing but then the generated classes are unusable in objective-C because not visible to objective-C (see my other issue in protobuf-swift https://github.com/alexeyxo/protobuf-swift/issues/65)

**Comment by alexeyxo** [comment]
Look this issue:
https://github.com/alexeyxo/protobuf-objc/issues/33#
