### ISSUE TITLE
fatal error: 'google/protobuf/compiler/plugin.h' file not found

### ISSUE THREAD

**Issue by Heroic-Niu** [alexeyxo/protobuf-objc#50]
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src/compiler
g++ -DHAVE_CONFIG_H -I. -I../..     -I/usr/local/include -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cc
main.cc:17:10: fatal error: 'google/protobuf/compiler/plugin.h' file not found
#include <google/protobuf/compiler/plugin.h>
         ^
1 error generated.
make[2]: *** [main.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
$ make install
Making install in src/compiler
g++ -DHAVE_CONFIG_H -I. -I../..     -I/usr/local/include -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cc
main.cc:17:10: fatal error: 'google/protobuf/compiler/plugin.h' file not found
#include <google/protobuf/compiler/plugin.h>
         ^
1 error generated.
make[1]: *** [main.o] Error 1
make: *** [install-recursive] Error 1

**Comment by alexeyxo** [comment]
Take a look instruction for installation:
https://github.com/alexeyxo/protobuf-objc#building-the-objective-c-protobuf-compiler
