### ISSUE TITLE
How to deal with property name started with 'newxxxxx'

### ISSUE THREAD

**Issue by huji0624** [alexeyxo/protobuf-objc#51]
compile error if I have some property name started with 'new',And I can't change the property name right now.

**Comment by alexeyxo** [comment]
I can't reproduce this problem, give me example, please.

**Comment by huji0624** [comment]
message OneName {
    required string newPhone = 1; 
}

If I have this protocol defined,it will compile a objective-c class   OneName with property "@property(nonatomic,strong) NSString *newPhone;",but when use arc,It will compile with error.

**Comment by alexeyxo** [comment]
Your example works fine. I can't reproduce.

**Comment by huji0624** [comment]
try this one.

message OneName {
repeated string new_fee_info = 1; 
}

**Comment by alexeyxo** [comment]
Fixed. Thanks.
