### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by geeknizer** [alexeyxo/protobuf-objc#53]
When i build with Xcode I get:

Ld /Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Products/Debug-iphonesimulator/GT.app/GT normal x86_64
    cd /Users/tarandeep/Documents/GT/GT
    export IPHONEOS_DEPLOYMENT_TARGET=8.4
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Products/Debug-iphonesimulator -F/Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Products/Debug-iphonesimulator -F/Users/tarandeep/Documents/GT/GT/Pods/GoogleMaps/Frameworks -filelist /Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Intermediates/GT.build/Debug-iphonesimulator/GT.build/Objects-normal/x86_64/GT.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lc++ -licucore -lz -framework AVFoundation -framework Accelerate -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreText -framework GLKit -framework GoogleMaps -framework ImageIO -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.4 -framework CoreFoundation -Xlinker -dependency_info -Xlinker /Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Intermediates/GT.build/Debug-iphonesimulator/GT.build/Objects-normal/x86_64/GT_dependency_info.dat -o /Users/tarandeep/Library/Developer/Xcode/DerivedData/GT-doybmghqampnllbmnubwspapuhbj/Build/Products/Debug-iphonesimulator/GT.app/GT

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PBExtensionRegistry", referenced from:
      objc-class-ref in Level.pb.o
  "_OBJC_CLASS_$_PBGeneratedMessage", referenced from:

**Comment by alexeyxo** [comment]
How you installed runtime library? Check your project settings. I think "ProtocolBuffers.h" not found.
