### ISSUE TITLE
Adding WatchOS support for Obj-C

### ISSUE THREAD

**Issue by Subu1449** [alexeyxo/protobuf-objc#61]
Is there anyway to add WatchOS2 support to Protocol Buffer - Objective-C? CocoaPods 0.38 added support for WatchOS however, in order for Pods to be usable with WatchOS2, they require the pod Author/Maintainer to add the following line in the Podspec:
s.watchos.deployment_target = '2.0' to https://github.com/alexeyxo/protobuf-objc/blob/master/ProtocolBuffers.podspec

This is outlined here: http://blog.cocoapods.org/CocoaPods-0.38/ (under the heading WatchOS). would this be possible?

**Comment by alexeyxo** [comment]
Done.
