### ISSUE TITLE
This file was generated by a newer version of protoc

### ISSUE THREAD

**Issue by EddyInWind** [alexeyxo/protobuf-objc#64]
Hi, I followed the tutorial step by step. 
1. Check if you have Homebrew brew -v
2. If you don't already have Homebrew, then install it ruby -e "$(curl -fsSL      https://raw.githubusercontent.com/Homebrew/install/master/install)"
3. Install the main Protobuf compiler and required tools brew install automake brew install libtool brew  install protobuf
4. (optional) Create a symlink to your Protobuf compiler. ln -s /usr/local/Cellar/protobuf/2.6.1/bin/protoc /usr/local/bin
5. Clone this repository. git clone https://github.com/alexeyxo/protobuf-objc.git
6. Build it! ./scripts/build.sh

But when I wanted to build it with the final one "./scripts/build.sh", 
I got the following error messages...

///************************************Error Messages*********************************************///
In file included from objc_extension.cc:19:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
mv -f .deps/main.Tpo .deps/main.Po
g++ -DHAVE_CONFIG_H -I. -I../..     -I/usr/local/include -MT objc_helpers.o -MD -MP -MF .deps/objc_helpers.Tpo -c -o objc_helpers.o objc_helpers.cc
In file included from objc_generator.cc:22:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
In file included from objc_primitive_field.cc:25:
In file included from /usr/local/include/google/protobuf/wire_format.h:43:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
In file included from objc_enum.cc:24:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
In file included from objc_file.cc:23:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
In file included from objc_enum_field.cc:25:
In file included from /usr/local/include/google/protobuf/wire_format.h:43:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
In file included from objc_message_field.cc:24:
In file included from /usr/local/include/google/protobuf/wire_format.h:43:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
4 errors generated.
4 errors generated.
4 errors generated.
make[2]: *** [objc_generator.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [objc_extension.o] Error 1
4 errors generated.
make[2]: *** [objc_enum.o] Error 1
4 errors generated.
make[2]: *** [objc_primitive_field.o] Error 1
4 errors generated.
make[2]: *** [objc_message_field.o] Error 1
make[2]: *** [objc_enum_field.o] Error 1
In file included from objc_helpers.cc:18:
In file included from ./objc_helpers.h:23:
./google/protobuf/descriptor.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
./google/protobuf/descriptor.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
./google/protobuf/descriptor.pb.h:14:2: error: your headers.
#error your headers.
 ^
./google/protobuf/descriptor.pb.h:26:10: fatal error: 'google/protobuf/generated_enum_reflection.h' file not found
#include <google/protobuf/generated_enum_reflection.h>
         ^
4 errors generated.
make[2]: *** [objc_helpers.o] Error 1
4 errors generated.
make[2]: *** [objc_file.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2 
///************************************Error Messages*********************************************///

I don't know how to do now. Can anyone help ? 
Thanks a lot.

**Comment by alexeyxo** [comment]
Hi! I think, you use ProtocolBuffers version 3.0. ProtocolBuffers 3.0 currently not supported.
Try this:
```protoc --version```

**Comment by EddyInWind** [comment]
Hi alexeyxo, I tried it and I got the response
libprotoc 2.2.0

Is there any possibility that I don't install the protoc correctly ?
Thank you.

**Comment by alexeyxo** [comment]
This is very old version of protoc. You should to update for 2.6.
With ```Homebrew```:
```brew update && brew upgrade && brew install protobuf```
