### ISSUE TITLE
How to set objc-options?

### ISSUE THREAD

**Issue by 4ntoine** [alexeyxo/protobuf-objc#66]
My .proto file has objc options:

```
syntax = "proto2";

package CompilerRPC;

// obj-c
import "objectivec-descriptor.proto";
option (google.protobuf.objectivec_file_options).package = "CompilerRPC";
option (google.protobuf.objectivec_file_options).class_prefix = "ASDTO";
option (google.protobuf.objectivec_file_options).relax_camel_case = true;
...
```

When trying to compile the files i'm getting an error:

> MBA-Anton:ArduinoCode asmirnov$ protoc --objc_out=/tmp/ ./auth.proto 
objectivec-descriptor.proto: File not found.
auth.proto: Import "objectivec-descriptor.proto" was not found or had errors.
MBA-Anton:ArduinoCode asmirnov$ 

if i comment this lines i'm able to generate .h/.m files

**Comment by alexeyxo** [comment]
You are using not correct path for ```objectivec-descriptor.proto```.
Create folder ```<your .proto files folder>/google/protobuf```.
You should use ```protoc --proto_path=``` flag.
https://code.google.com/p/metasyntactic/issues/detail?id=135

**Comment by 4ntoine** [comment]
i've followed https://github.com/alexeyxo/protobuf-objc, consider editing it as needed.

still not clear:
1. created folder 'google/protobuf'
2. edited file to 'import "google/protobuf/objectivec-descriptor.proto";'
3. invoke 

'MBA-Anton:ArduinoCode asmirnov$ protoc --objc_out=/tmp/ ./auth.proto --proto_path=.
google/protobuf/objectivec-descriptor.proto: File not found.
auth.proto: Import "google/protobuf/objectivec-descriptor.proto" was not found or had errors.
MBA-Anton:ArduinoCode asmirnov$ ls ./google/protobuf/
MBA-Anton:ArduinoCode asmirnov$'

**Comment by 4ntoine** [comment]
i've managed it by copying all /google/protobuf files from this repo to my project. is is required? IMHO It's not good to have this dependencies in my project as it relates to tool not to the project itself.

**Comment by alexeyxo** [comment]
Another method does not exist. So working plugin in Protocol Buffers.
