### ISSUE TITLE
proto 2.5

### ISSUE THREAD

**Issue by bickster** [alexeyxo/protobuf-objc#68]
Hi,

Is it possible to use proto 2.5 instead of 2.6? If so, is there any documentation on how to build the project for 2.5?

Thanks,
Chris

**Comment by alexeyxo** [comment]
You can update ```descriptor.proto``` version 2.6  in ```google/protobuf``` folder for ```descriptor.proto`` versions 2.5 and run ```./scripts/makeDescriptor.sh```.
