### ISSUE TITLE
How to make this compatible with compiling to python?

### ISSUE THREAD

**Issue by samskiter** [alexeyxo/protobuf-objc#69]
I've added the import and FileOption lines to my proto file, but now I can't compile it to python any more.

Essentially, I need to compile the objectivec_descriptor as well. I can do this, but it ends up in a folder called "google/protobuf". This then conflicts with namespacing of the python protobuf module (which defines "google/protobuf" as well) so python cannot find the objectivec_descriptor. Which leads me to ask: should this project be using the google namespace?

I've tried just making a shim proto file just for iOS, which sets up the FileOptions and imports the real proto file, but that doesn't work - the options only seem to apply to the file they are set in.

So I'm a bit stumped. I clearly need just one proto file, but when I'm compiling that to python I get into a big mess, mainly because of namespacing.

Can you offer any advice?

FYI, I also sought some advice on the main protobuf project, before I got to the root of the problem - see here: https://github.com/google/protobuf/issues/995

**Comment by alexeyxo** [comment]
Unfortunately, I never used ProtocolBuffers in python projects. And I had forgotten python:(

**Comment by samskiter** [comment]
So I did try moving your code out of of the google namespace. And, after adding __init__.py to the folders that the protobuf-python compilation spat out I got a working system.

I would rather that protoc ignored the objective-c extension when not using it, but I don't think that's easy with the simplistic way extensions are done
