### ISSUE TITLE
not support map data type?

### ISSUE THREAD

**Issue by winneryong** [alexeyxo/protobuf-objc#70]
Hi
I see language description in google official site say:
"The generated map API is currently available for all proto2 supported languages. "

How lang time can support map data type please?

version: libprotoc 2.6.1

IDL:
syntax = "proto2";
message ErrorResponse {
	required uint32 errorCode = 1;
	map<string, string> additional = 4;
}

Error message below:

IMCommon.proto:11:9: Expected "required", "optional", or "repeated".
IMCommon.proto:11:12: Expected field name.
IMCommon.proto:11:9: Expected "required", "optional", or "repeated".
IMCommon.proto:11:12: Expected field name.

**Comment by winneryong** [comment]
version: libprotoc 2.6.1

**Comment by alexeyxo** [comment]
```syntax ="proto2";``` available only in protobuf version of 3.0 . Protobuf 3.0 not supported yet.

**Comment by winneryong** [comment]
thanks
