### ISSUE TITLE
Build Fail #import <ProtocolBuffers/ProtocolBuffers.h> Not Found

### ISSUE THREAD

**Issue by ido-ran** [alexeyxo/protobuf-objc#74]
Hi,
I fail to use the CocoaPods because it require the use of workspace which currently is a bit problematic for me.
I'm trying to add the runtime project (ProtocolBuffers.xcodeproj) to my project but when I try to build it I get error of ProtocolBuffers/ProtocolBuffers.h file not found.

What am I doing wrong?

**Comment by alexeyxo** [comment]
You need setup "header search path" in current project.

**Comment by ido-ran** [comment]
Thanks for the super quick response. I did but there is no file name ProtocolBuffers.h directly under ProtocolBuffers directory - there is a directory call Classes in the middle.

**Comment by alexeyxo** [comment]
This header is located  in the ``Framework``` folder.
