### ISSUE TITLE
Duplicate symbol cause clang error

### ISSUE THREAD

**Issue by miguelarauj1o** [alexeyxo/protobuf-objc#80]
Hello, I have two .proto files: event.proto and user_tracking.proto, each one has a message body with the same name: `message WifiScanProto { ... }`

So, after building the project in Xcode, I'm getting this error:
```
duplicate symbol _OBJC_IVAR_$_WifiScanApProto.hasMac_ in:
/pathToLib.a(User_tracking.pb.o)
/pathToLib.a(Event.pb.o)
ld: 1 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I java, `option java_package = "..."`; can solve this. But, how I can solve this in ObjC?

**Comment by alexeyxo** [comment]
Objc has not support "nested" messages or packages. This is problem of language but not protobuf.

**Comment by miguelarauj1o** [comment]
Yeah, but I found a workaround. Anyway, Thanks for the quick response.
